import {
  User,
  adsImg,
  ups,
  dhl,
  ips,
  usps,
  UserProfile,
  CertificateImg,
  StatsOne,
  StatsTwo,
  StatsThree,
  MenteeProfile,
  Statsdoller,
  pmScales,
  pmScreen,
  pmLaptop,
  pmBoxLabel,
  services1,
  services2,
  services3,
  services4,
} from "../assets/images";

export const roles = {
  admin: 1,
  mentor: 2,
  mentee: 3,
};

// New Objects START
export const featuresCardData = [
  {
    id: 1,
    text: "Lorem ipsum dolor sit amet",
    tag: "save",
  },
  {
    id: 2,
    text: "Lorem ipsum dolor sit amet",
    tag: "Discounted",
  },
  {
    id: 3,
    text: "Lorem ipsum dolor sit amet",
    tag: "Instant",
  },
  {
    id: 4,
    text: "Lorem ipsum dolor sit amet",
    tag: "Compare",
  },
];

export const aboutData = [
  {
    id: 1,
    title: "Lorem ipsum dolor sit amet",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, totam amet aliquid quas veniam atque temporibus magnam",
  },
];

export const brandSliderData = [
  {
    id: 1,
    testimonialimage: ups,
  },
  {
    id: 2,
    testimonialimage: dhl,
  },
  {
    id: 3,
    testimonialimage: ips,
  },
  {
    id: 4,
    testimonialimage: usps,
  },
  {
    id: 5,
    testimonialimage: ups,
  },
];

export const packagesCardData = [
  {
    id: 1,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque,",
    packageimage: pmScales,
  },
  {
    id: 2,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque,",
    packageimage: pmScreen,
  },
  {
    id: 3,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque,",
    packageimage: pmLaptop,
  },
  {
    id: 4,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque,",
    packageimage: pmBoxLabel,
  },
];

export const servicesCardData = [
  {
    id: 1,
    title: "Lorem ipsum dolor",
    text: "Lorem ipsum dolor sit amet consectetur",
    serviceimage: services1,
  },
  {
    id: 2,
    title: "Lorem ipsum dolor",
    text: "Lorem ipsum dolor sit amet consectetur",
    serviceimage: services2,
  },
  {
    id: 3,
    title: "Lorem ipsum dolor",
    text: "Lorem ipsum dolor sit amet consectetur",
    serviceimage: services3,
  },
  {
    id: 4,
    title: "Lorem ipsum dolor",
    text: "Lorem ipsum dolor sit amet consectetur",
    serviceimage: services4,
  },
];

export const orderLogsData = [
  {
    id: 1,
    orderNo: "123456",
    trackingNo: "123456",
    totalPrice: "$2000",
    totalWeight: "100 KG",
    startOrder: "MM/DD/YYYY",
    endOrder: "MM/DD/YYYY",
    status: "completed",
    shippingCarrier: "ABC",
    noParcels: "01",
    pickUpGenerated: "MM/DD/YYYY",
    estimatedDeliveryDate: "MM/DD/YYYY",
    deliveryType: "Urgent",
    action: true,
    pickupDetails: {
        yourContactNo: "123",
        accountNo: "12345678",
        name: "ABC",
        addressLine1: "Xyz 123, Abc",
        addressLine2: "Xyz 123, Abc",
        city: "Xyz",
        state: "Albama",
        zipCode: "0000",
        earliestPickupTime: "HH:MM AM",
        latestPickupTime: "HH:MM AM",
        specialInstructions:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismodn gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montesnascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus.",
      },
    dropoffDetails:{
        contactNoReceiver: "001929361723",
        country: "USA",
        name: "ABC",
        addressLine1: "Xyz 123, Abc",
        addressLine2: "Xyz 123, Abc",
        city: "Xyz",
        state: "Albama",
        zipCode: "0000",
        estimatedDeliveryTime: "HH:MM AM",
        specialInstructions:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismodn gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montesnascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus.",
      },

  },
  {
    id: 2,
    orderNo: "123456",
    trackingNo: "123456",
    totalPrice: "$1000",
    totalWeight: "100 KG",
    startOrder: "MM/DD/YYYY",
    endOrder: "MM/DD/YYYY",
    status: "completed",
    action: true,
    pickupDetails: {
      yourContactNo: "123",
      accountNo: "12345678",
      name: "ABC",
      addressLine1: "Xyz 123, Abc",
      addressLine2: "Xyz 123, Abc",
      city: "Xyz",
      state: "Albama",
      zipCode: "0000",
      earliestPickupTime: "HH:MM AM",
      latestPickupTime: "HH:MM AM",
      specialInstructions:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismodn gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montesnascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus.",
    },

    dropoffDetails: {
      contactNoReceiver: "001929361723",
      country: "USA",
      name: "ABC",
      addressLine1: "Xyz 123, Abc",
      addressLine2: "Xyz 123, Abc",
      city: "Xyz",
      state: "Albama",
      zipCode: "0000",
      estimatedDeliveryTime: "HH:MM AM",
      specialInstructions:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismodn gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montesnascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus.",
    },
  },
  {
    id: 3,
    orderNo: "123456",
    trackingNo: "123456",
    totalPrice: "$1000",
    totalWeight: "100 KG",
    startOrder: "MM/DD/YYYY",
    endOrder: "MM/DD/YYYY",
    status: "cancelled",
    action: true,
    pickupDetails: {
      yourContactNo: "123",
      accountNo: "12345678",
      name: "ABC",
      addressLine1: "Xyz 123, Abc",
      addressLine2: "Xyz 123, Abc",
      city: "Xyz",
      state: "Albama",
      zipCode: "0000",
      earliestPickupTime: "HH:MM AM",
      latestPickupTime: "HH:MM AM",
      specialInstructions:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismodn gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montesnascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus.",
    },

    dropoffDetails: {
      contactNoReceiver: "001929361723",
      country: "USA",
      name: "ABC",
      addressLine1: "Xyz 123, Abc",
      addressLine2: "Xyz 123, Abc",
      city: "Xyz",
      state: "Albama",
      zipCode: "0000",
      estimatedDeliveryTime: "HH:MM AM",
      specialInstructions:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismodn gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montesnascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus.",
    },
  },
  {
    id: 4,
    orderNo: "123456",
    trackingNo: "123456",
    totalPrice: "$1000",
    totalWeight: "100 KG",
    startOrder: "MM/DD/YYYY",
    endOrder: "MM/DD/YYYY",
    status: "cancelled",
    action: true,
    pickupDetails: {
      yourContactNo: "123",
      accountNo: "12345678",
      name: "ABC",
      addressLine1: "Xyz 123, Abc",
      addressLine2: "Xyz 123, Abc",
      city: "Xyz",
      state: "Albama",
      zipCode: "0000",
      earliestPickupTime: "HH:MM AM",
      latestPickupTime: "HH:MM AM",
      specialInstructions:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismodn gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montesnascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus.",
    },

    dropoffDetails: {
      contactNoReceiver: "001929361723",
      country: "USA",
      name: "ABC",
      addressLine1: "Xyz 123, Abc",
      addressLine2: "Xyz 123, Abc",
      city: "Xyz",
      state: "Albama",
      zipCode: "0000",
      estimatedDeliveryTime: "HH:MM AM",
      specialInstructions:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismodn gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montesnascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus.",
    },
  },
  {
    id: 5,
    orderNo: "123456",
    trackingNo: "123456",
    totalPrice: "$1000",
    totalWeight: "100 KG",
    startOrder: "MM/DD/YYYY",
    endOrder: "MM/DD/YYYY",
    status: "pending",
    action: true,
    pickupDetails: {
      yourContactNo: "123",
      accountNo: "12345678",
      name: "ABC",
      addressLine1: "Xyz 123, Abc",
      addressLine2: "Xyz 123, Abc",
      city: "Xyz",
      state: "Albama",
      zipCode: "0000",
      earliestPickupTime: "HH:MM AM",
      latestPickupTime: "HH:MM AM",
      specialInstructions:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismodn gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montesnascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus.",
    },

    dropoffDetails: {
      contactNoReceiver: "001929361723",
      country: "USA",
      name: "ABC",
      addressLine1: "Xyz 123, Abc",
      addressLine2: "Xyz 123, Abc",
      city: "Xyz",
      state: "Albama",
      zipCode: "0000",
      estimatedDeliveryTime: "HH:MM AM",
      specialInstructions:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismodn gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montesnascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus.",
    },
  },
  {
    id: 6,
    orderNo: "123456",
    trackingNo: "123456",
    totalPrice: "$1000",
    totalWeight: "100 KG",
    startOrder: "MM/DD/YYYY",
    endOrder: "MM/DD/YYYY",
    status: "pending",
    action: true,
    pickupDetails: {
      yourContactNo: "123",
      accountNo: "12345678",
      name: "ABC",
      addressLine1: "Xyz 123, Abc",
      addressLine2: "Xyz 123, Abc",
      city: "Xyz",
      state: "Albama",
      zipCode: "0000",
      earliestPickupTime: "HH:MM AM",
      latestPickupTime: "HH:MM AM",
      specialInstructions:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismodn gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montesnascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus.",
    },

    dropoffDetails: {
      contactNoReceiver: "001929361723",
      country: "USA",
      name: "ABC",
      addressLine1: "Xyz 123, Abc",
      addressLine2: "Xyz 123, Abc",
      city: "Xyz",
      state: "Albama",
      zipCode: "0000",
      estimatedDeliveryTime: "HH:MM AM",
      specialInstructions:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismodn gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montesnascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus.",
    },
  },
];

export const faqData = [
  {
    id: "1",
    faqTitle: "How do you ship your parcel?",
    faqAnswer: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
  },
  {
    id: "2",
    faqTitle: "What are your transit times?",
    faqAnswer: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
  },
  {
    id: "3",
    faqTitle: "How do i ship with your company?",
    faqAnswer: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
  },
  {
    id: "4",
    faqTitle: "Why are your prices cheaper even though you are using major carriers?",
    faqAnswer: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
  },
  {
    id: "5",
    faqTitle: "What is custom clearance?",
    faqAnswer: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
  },
  {
    id: "6",
    faqTitle: "Do you clear packages through customs?",
    faqAnswer: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
  },
  {
    id: "7",
    faqTitle: "What are dimensional weight?",
    faqAnswer: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
  },
  {
    id: "8",
    faqTitle: "Do you have any warranty?",
    faqAnswer: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
  },
  {
    id: "9",
    faqTitle: "Are there any additional fees?",
    faqAnswer: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
  },
  {
    id: "10",
    faqTitle: "Do you have any warranty?",
    faqAnswer: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
  },
]

export const notificationData = [
  {
    id: "01",
    content: "Lorem Ipsum is simply dummy text ",
    notPara: "Lorem Ipsum is simply dummy text.",
    date: "01/01/2022",
    time: "01 sec ago",
    read: false,
  },
  {
    id: "02",
    content: "Lorem Ipsum is simply dummy text asdasdas",
    notPara: "Lorem Ipsum is simply dummy text.",
    date: "01/01/2022",
    time: "02 hour ago",
    read: true,
  },
  {
    id: "03",
    content: "Lorem Ipsum is simply dummy text adsadasd3",
    notPara: "Lorem Ipsum is simply dummy text.",
    date: "01/01/2022",
    time: "02 hour ago",
    read: false,
  },
  {
    id: "04",
    content: "Lorem Ipsum is simply dummy text ",
    notPara: "Lorem Ipsum is simply dummy text.",
    date: "Dec 19, 2020",
    time: "02 hour ago",
    read: true,
  },
  {
    id: "05",
    content: "Lorem Ipsum is simply dummy text ",
    notPara: "Lorem Ipsum is simply dummy text.",
    date: "01/01/2022",
    time: "02 hour ago",
    read: true,
  },
];

// New Objects END

export const SERVER_URL = "http://localhost:8000/";
// export const SERVER_URL = "https://dev74.onlinetestingserver.com/acolai/";

export const status = {
  pending: "pending",
  requested: "requested",
  rejected: "rejected",
  req_accepted: "request accepted",
  req_rejected: "request rejected",
  contacted: "contacted",
};
export const mentorshipStatusFilter = [
  "pending",
  "requested",
  "rejected",
  "request accepted",
  "request rejected",
  "contacted",
];

export const authCredentials = [
  {
    email: "mentor@gmail.com",
    password: "mentor123",
    role: "mentor",
  },
  {
    email: "mentee@gmail.com",
    password: "mentee123",
    role: "mentee",
  },
];

export const userProfileData = {
  image: UserProfile,
  name: "Tom Albert",
  email: "tomalbert@gmail.com",
  number: "+19159969739",
  areaInterst: "Interest ABC, Interest ABC, Interest ABC",
  about:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.  tempor. Cum sociis natoque penatibus et magnis dis parturient.  Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar",
  institutename: "Institute ABC",
  degreeTitle: "Degree ABC",
  year: "2020 - 2023",
  OrganizationName: "Organization ABC",
  Designation: "Doctor A",
  certificate: "Abc Certificate Title",
  certificateImage: CertificateImg,
};
export const featuredCardData = [
  {
    id: 1,
    cardimage: adsImg,
    userimage: User,
    name: "Mark Jeson",
    text: "Online Session",
    hours: "$20/Hr",
    about: "Area Of Interest",
    sports: "Cooking, Sports, Traveling",
  },
  {
    id: 2,
    cardimage: adsImg,
    userimage: User,
    name: "Mark Jeson",
    text: "Online Session",
    hours: "$20/Hr",
    about: "Area Of Interest",
    sports: "Cooking, Sports, Traveling",
  },
  {
    id: 4,
    cardimage: adsImg,
    userimage: User,
    name: "Mark Jeson",
    text: "Online Session",
    hours: "$20/Hr",
    about: "Area Of Interest",
    sports: "Cooking, Sports, Traveling",
  },
  {
    id: 5,
    cardimage: adsImg,
    userimage: User,
    name: "Mark Jeson",
    text: "Online Session",
    hours: "$20/Hr",
    about: "Area Of Interest",
    sports: "Cooking, Sports, Traveling",
  },
  {
    id: 6,
    cardimage: adsImg,
    userimage: User,
    name: "Mark Jeson",
    text: "Online Session",
    hours: "$20/Hr",
    about: "Area Of Interest",
    sports: "Cooking, Sports, Traveling",
  },
  {
    id: 7,
    cardimage: adsImg,
    userimage: User,
    name: "Mark Jeson",
    text: "Online Session",
    hours: "$20/Hr",
    about: "Area Of Interest",
    sports: "Cooking, Sports, Traveling",
  },
  {
    id: 8,
    cardimage: adsImg,
    userimage: User,
    name: "Mark Jeson",
    text: "Online Session",
    hours: "$20/Hr",
    about: "Area Of Interest",
    sports: "Cooking, Sports, Traveling",
  },
  {
    id: 10,
    cardimage: adsImg,
    userimage: User,
    name: "Mark Jeson",
    text: "Online Session",
    hours: "$20/Hr",
    about: "Area Of Interest",
    sports: "Cooking, Sports, Traveling",
  },
  {
    id: 11,
    cardimage: adsImg,
    userimage: User,
    name: "Mark Jeson",
    text: "Online Session",
    hours: "$20/Hr",
    about: "Area Of Interest",
    sports: "Cooking, Sports, Traveling",
  },
  {
    id: 12,
    cardimage: adsImg,
    userimage: User,
    name: "Mark Jeson",
    text: "Online Session",
    hours: "$20/Hr",
    about: "Area Of Interest",
    sports: "Cooking, Sports, Traveling",
  },
  {
    id: 13,
    cardimage: adsImg,
    userimage: User,
    name: "Mark Jeson",
    text: "Online Session",
    hours: "$20/Hr",
    about: "Area Of Interest",
    sports: "Cooking, Sports, Traveling",
  },
  {
    id: 14,
    cardimage: adsImg,
    userimage: User,
    name: "Mark Jeson",
    text: "Online Session",
    hours: "$20/Hr",
    about: "Area Of Interest",
    sports: "Cooking, Sports, Traveling",
  },
];
export const ourAdsData = [
  {
    id: 1,
    cardimage: adsImg,
    userimage: User,
    name: "Mark Jeson",
    text: "Online Session",
    hours: "$20/Hr",
    about: "Area Of Interest",
    sports: "Cooking, Sports, Traveling",
  },
  {
    id: 2,
    cardimage: adsImg,
    userimage: User,
    name: "Mark Jeson",
    text: "Online Session",
    hours: "$20/Hr",
    about: "Area Of Interest",
    sports: "Cooking, Sports, Traveling",
  },
  {
    id: 4,
    cardimage: adsImg,
    userimage: User,
    name: "Mark Jeson",
    text: "Online Session",
    hours: "$20/Hr",
    about: "Area Of Interest",
    sports: "Cooking, Sports, Traveling",
  },
  {
    id: 5,
    cardimage: adsImg,
    userimage: User,
    name: "Mark Jeson",
    text: "Online Session",
    hours: "$20/Hr",
    about: "Area Of Interest",
    sports: "Cooking, Sports, Traveling",
  },
  {
    id: 6,
    cardimage: adsImg,
    userimage: User,
    name: "Mark Jeson",
    text: "Online Session",
    hours: "$20/Hr",
    about: "Area Of Interest",
    sports: "Cooking, Sports, Traveling",
  },
  {
    id: 7,
    cardimage: adsImg,
    userimage: User,
    name: "Mark Jeson",
    text: "Online Session",
    hours: "$20/Hr",
    about: "Area Of Interest",
    sports: "Cooking, Sports, Traveling",
  },
];

export const MentorshipReqData = [
  {
    id: 1,
    srNo: "01",
    UserImg: User,
    requeststatus: "Pending",
    requestid: "Abc-123",
    reqamount: "$12",
    firstname: "Mark Jeson",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "orem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
  },
  {
    id: 2,
    srNo: "02",
    UserImg: User,
    requeststatus: "Rejected",
    requestid: "Abc-123",
    reqamount: "$12",
    firstname: "jonson",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
  },
  {
    id: 3,
    srNo: "03",
    UserImg: User,
    requeststatus: "Requested",
    requestid: "Abc-123",
    reqamount: "$12",
    firstname: "Mickel",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
  },
  {
    id: 4,
    srNo: "04",
    UserImg: User,
    requeststatus: "Request - Accepted",
    requestid: "Abc-123",
    reqamount: "$12",
    firstname: "jao fleps",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
  },
  {
    id: 5,
    srNo: "05",
    UserImg: User,
    requeststatus: "Request - Rejected",
    requestid: "Abc-123",
    reqamount: "$12",
    firstname: "mark ",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "orem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
  },
  {
    id: 6,
    srNo: "06",
    UserImg: User,
    requeststatus: "Accepted",
    requestid: "Abc-123",
    reqamount: "$12",
    firstname: "Cris gyle",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
  },
  {
    id: 7,
    srNo: "07",
    UserImg: User,
    requeststatus: "Contacted",
    requestid: "Abc-123",
    reqamount: "$12",
    firstname: "Cris gyle",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
  },
];
export const featuringLogsData = [
  {
    id: 1,
    srNo: "01",
    status: true,
    FeatureAdTitle: "Abc Ad Title",
    SubscriptionDate: "01/01/2022",
    RequestsReceived: "255",
    RemainingRequests: "12",
  },
  {
    id: 2,
    srNo: "02",
    status: false,
    FeatureAdTitle: "cde Ad Title",
    SubscriptionDate: "01/01/2022",
    RequestsReceived: "11",
    RemainingRequests: "05",
  },
  {
    id: 3,
    srNo: "03",
    status: true,
    FeatureAdTitle: "cde Ad Title",
    SubscriptionDate: "01/01/2022",
    RequestsReceived: "25",
    RemainingRequests: "211",
  },
  {
    id: 4,
    srNo: "04",
    status: false,
    FeatureAdTitle: "New oneTitle",
    SubscriptionDate: "10/01/2020",
    RequestsReceived: "11",
    RemainingRequests: "05",
  },
  {
    id: 5,
    srNo: "05",
    status: true,
    FeatureAdTitle: "New oneTitle",
    SubscriptionDate: "10/01/2020",
    RequestsReceived: "11",
    RemainingRequests: "05",
  },
  {
    id: 6,
    srNo: "06",
    status: false,
    FeatureAdTitle: "New oneTitle",
    SubscriptionDate: "10/01/2020",
    RequestsReceived: "11",
    RemainingRequests: "05",
  },
];
export const adsLogsdata = [
  {
    id: 1,
    srNo: "01",
    status: true,
    FeatureAdTitle: "Abc Ad Title",
    SubscriptionDate: "01/01/2022",
    RequestsReceived: "255",
    RemainingRequests: "12",
  },
  {
    id: 2,
    srNo: "02",
    status: false,
    FeatureAdTitle: "cde Ad Title",
    SubscriptionDate: "01/01/2022",
    RequestsReceived: "11",
    RemainingRequests: "05",
  },
  {
    id: 3,
    srNo: "03",
    status: true,
    FeatureAdTitle: "cde Ad Title",
    SubscriptionDate: "01/01/2022",
    RequestsReceived: "25",
    RemainingRequests: "211",
  },
  {
    id: 4,
    srNo: "04",
    status: false,
    FeatureAdTitle: "New oneTitle",
    SubscriptionDate: "10/01/2020",
    RequestsReceived: "11",
    RemainingRequests: "05",
  },
  {
    id: 5,
    srNo: "05",
    status: true,
    FeatureAdTitle: "New oneTitle",
    SubscriptionDate: "10/01/2020",
    RequestsReceived: "11",
    RemainingRequests: "05",
  },
  {
    id: 6,
    srNo: "06",
    status: false,
    FeatureAdTitle: "New oneTitle",
    SubscriptionDate: "10/01/2020",
    RequestsReceived: "11",
    RemainingRequests: "05",
  },
];
export const packagesData = [
  {
    id: 1,
    title: "Gold",
    price: "$30",
    request: "20 Requests",
    text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    list1: "Lorem Ipsum is simply dummy text.",
    list2: "Lorem Ipsum is simply dummy text.",
    list3: "Lorem Ipsum is simply dummy text.",
  },
  {
    id: 2,
    title: "Gold",
    price: "$50",
    request: "20 Requests",
    text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    list1: "Lorem Ipsum is simply dummy text.",
    list2: "Lorem Ipsum is simply dummy text.",
    list3: "Lorem Ipsum is simply dummy text.",
  },
  {
    id: 3,
    title: "Gold",
    price: "$60",
    request: "20 Requests",
    text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    list1: "Lorem Ipsum is simply dummy text.",
    list2: "Lorem Ipsum is simply dummy text.",
    list3: "Lorem Ipsum is simply dummy text.",
  },
];
export const chargesLogs = [
  {
    id: "1",
    srNo: "01",
    sessionCharges: "$11",
    sessionChargesTwo: "$12",
    requestdate: "10/11/2021",
  },
  {
    id: "2",
    srNo: "02",
    sessionCharges: "$11",
    sessionChargesTwo: "$12",
    requestdate: "10/11/2021",
  },
  {
    id: "3",
    srNo: "03",
    sessionCharges: "$11",
    sessionChargesTwo: "$12",
    requestdate: "10/11/2021",
  },
  {
    id: "4",
    srNo: "04",
    sessionCharges: "$11",
    sessionChargesTwo: "$12",
    requestdate: "10/11/2021",
  },
];

// Mentee data Start here
export const mentorDetailData = {
  id: 1,
  image: UserProfile,
  name: "Tom Albert",
  email: "tomalbert@gmail.com",
  number: "+19159969739",
  areaInterst: "Interest ABC, Interest ABC, Interest ABC",
  about:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.  tempor. Cum sociis natoque penatibus et magnis dis parturient.  Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar",
  institutename: "Institute ABC",
  degreeTitle: "Degree ABC",
  year: "2020 - 2023",
  OrganizationName: "Organization ABC",
  Designation: "Doctor A",
  certificate: "Abc Certificate Title",
  certificateImage: CertificateImg,
};
export const RequestData = [
  {
    id: 1,
    srNo: "01",
    UserImg: User,
    requeststatus: "Pending",
    requestid: "Abc-123",
    requestamount: "$123",
    firstname: "Mark Jeson",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "orem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
  },
  {
    id: 2,
    srNo: "02",
    UserImg: User,
    requeststatus: "Rejected",
    requestid: "Abc-123",
    requestamount: "$123",
    firstname: "jonson",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
  },
  {
    id: 3,
    srNo: "03",
    UserImg: User,
    requeststatus: "Requested",
    requestid: "Abc-123",
    requestamount: "$123",
    firstname: "Mickel",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
  },
  {
    id: 4,
    srNo: "04",
    UserImg: User,
    requeststatus: "Request - Accepted",
    requestid: "Abc-123",
    requestamount: "$123",
    firstname: "jao fleps",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
  },
  {
    id: 5,
    srNo: "05",
    UserImg: User,
    requeststatus: "Request - Rejected",
    requestid: "Abc-123",
    requestamount: "$123",
    firstname: "mark ",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "orem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
  },
  {
    id: 6,
    srNo: "06",
    UserImg: User,
    requeststatus: "Accepted",
    requestid: "Abc-123",
    requestamount: "$123",
    firstname: "Cris gyle",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
  },
  {
    id: 7,
    srNo: "07",
    UserImg: User,
    requeststatus: "Contacted",
    requestid: "Abc-123",
    requestamount: "$123",
    firstname: "Cris gyle",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
  },
];
// Mentee data End here

// Admin data start here
export const stats = [
  {
    id: 1,
    image: StatsOne,
    text: "NEW MENTEES",
  },
  {
    id: 2,
    image: StatsTwo,
    text: "NEW MENTORS",
  },
  {
    id: 3,
    image: Statsdoller,
    text: "TOTAL EARNING",
  },
  {
    id: 4,
    image: StatsThree,
    text: "TOTAL REQUESTS",
  },
];
export const MenteeManagementData = [
  {
    id: 1,
    srNo: "01",
    status: true,
    image: MenteeProfile,
    name: "Abc Ad Title",
    regDate: "01/01/2022",
    RequestsReceived: "255",
    email: "Info@Example.Com",
    phone: "+40-123-456-7890",
  },
  {
    id: 2,
    srNo: "02",
    image: MenteeProfile,
    phone: "+40-123-456-7890",
    status: false,
    name: "Abc Ad Title",
    regDate: "01/01/2022",
    RequestsReceived: "255",
    email: "Info@Example.Com",
  },
  {
    id: 3,
    srNo: "03",
    image: MenteeProfile,
    phone: "+40-123-456-7890",
    status: true,
    name: "Abc Ad Title",
    regDate: "01/01/2022",
    RequestsReceived: "255",
    email: "Info@Example.Com",
  },
  {
    id: 4,
    srNo: "04",
    image: MenteeProfile,
    phone: "+40-123-456-7890",
    status: false,
    name: "Abc Ad Title",
    regDate: "01/01/2022",
    RequestsReceived: "255",
    email: "Info@Example.Com",
  },
  {
    id: 5,
    srNo: "05",
    image: MenteeProfile,
    phone: "+40-123-456-7890",
    status: true,
    name: "Abc Ad Title",
    regDate: "01/01/2022",
    RequestsReceived: "255",
    email: "Info@Example.Com",
  },
  {
    id: 6,
    srNo: "06",
    image: MenteeProfile,
    phone: "+40-123-456-7890",
    status: false,
    name: "Abc Ad Title",
    regDate: "01/01/2022",
    RequestsReceived: "255",
    email: "Info@Example.Com",
  },
];
export const MentorManagementData = [
  {
    id: 1,
    srNo: "01",
    status: true,
    image: MenteeProfile,
    name: "Abc Ad Title",
    regDate: "01/01/2022",
    RequestsReceived: "255",
    email: "Info@Example.Com",
    phone: "+40-123-456-7890",
    number: "+19159969739",
    areaInterst: "Interest ABC, Interest ABC, Interest ABC",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.  tempor. Cum sociis natoque penatibus et magnis dis parturient.  Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar",
    institutename: "Institute ABC",
    degreeTitle: "Degree ABC",
    year: "2020 - 2023",
    OrganizationName: "Organization ABC",
    Designation: "Doctor A",
    certificate: "Abc Certificate Title",
    certificateImage: CertificateImg,
  },
  {
    id: 2,
    srNo: "02",
    status: true,
    image: MenteeProfile,
    name: "Abc Ad Title",
    regDate: "01/01/2022",
    RequestsReceived: "255",
    email: "Info@Example.Com",
    phone: "+40-123-456-7890",
    number: "+19159969739",
    areaInterst: "Interest ABC, Interest ABC, Interest ABC",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.  tempor. Cum sociis natoque penatibus et magnis dis parturient.  Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar",
    institutename: "Institute ABC",
    degreeTitle: "Degree ABC",
    year: "2020 - 2023",
    OrganizationName: "Organization ABC",
    Designation: "Doctor A",
    certificate: "Abc Certificate Title",
    certificateImage: CertificateImg,
  },
  {
    id: 1,
    srNo: "01",
    status: true,
    image: MenteeProfile,
    name: "Abc Ad Title",
    regDate: "01/01/2022",
    RequestsReceived: "255",
    email: "Info@Example.Com",
    phone: "+40-123-456-7890",
    number: "+19159969739",
    areaInterst: "Interest ABC, Interest ABC, Interest ABC",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.  tempor. Cum sociis natoque penatibus et magnis dis parturient.  Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar",
    institutename: "Institute ABC",
    degreeTitle: "Degree ABC",
    year: "2020 - 2023",
    OrganizationName: "Organization ABC",
    Designation: "Doctor A",
    certificate: "Abc Certificate Title",
    certificateImage: CertificateImg,
  },
  {
    id: 4,
    srNo: "04",
    image: MenteeProfile,
    phone: "+40-123-456-7890",
    status: false,
    name: "Abc Ad Title",
    regDate: "01/01/2022",
    RequestsReceived: "255",
    email: "Info@Example.Com",
  },
  {
    id: 5,
    srNo: "05",
    image: MenteeProfile,
    phone: "+40-123-456-7890",
    status: true,
    name: "Abc Ad Title",
    regDate: "01/01/2022",
    RequestsReceived: "255",
    email: "Info@Example.Com",
  },
  {
    id: 6,
    srNo: "06",
    image: MenteeProfile,
    phone: "+40-123-456-7890",
    status: false,
    name: "Abc Ad Title",
    regDate: "01/01/2022",
    RequestsReceived: "255",
    email: "Info@Example.Com",
  },
];
export const mentorProfileData = [
  {
    id: 1,
    image: UserProfile,
    name: "Tom Albert",
    email: "tomalbert@gmail.com",
    number: "+19159969739",
    areaInterst: "Interest ABC, Interest ABC, Interest ABC",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.  tempor. Cum sociis natoque penatibus et magnis dis parturient.  Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar",
    institutename: "Institute ABC",
    degreeTitle: "Degree ABC",
    year: "2020 - 2023",
    OrganizationName: "Organization ABC",
    Designation: "Doctor A",
    certificate: "Abc Certificate Title",
    certificateImage: CertificateImg,
  },
  {
    id: 2,
    image: UserProfile,
    name: "Tom Albert",
    email: "tomalbert@gmail.com",
    number: "+19159969739",
    areaInterst: "Interest ABC, Interest ABC, Interest ABC",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.  tempor. Cum sociis natoque penatibus et magnis dis parturient.  Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar",
    institutename: "Institute ABC",
    degreeTitle: "Degree ABC",
    year: "2020 - 2023",
    OrganizationName: "Organization ABC",
    Designation: "Doctor A",
    certificate: "Abc Certificate Title",
    certificateImage: CertificateImg,
  },
  {
    id: 3,
    image: UserProfile,
    name: "Tom Albert",
    email: "tomalbert@gmail.com",
    number: "+19159969739",
    areaInterst: "Interest ABC, Interest ABC, Interest ABC",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.  tempor. Cum sociis natoque penatibus et magnis dis parturient.  Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar",
    institutename: "Institute ABC",
    degreeTitle: "Degree ABC",
    year: "2020 - 2023",
    OrganizationName: "Organization ABC",
    Designation: "Doctor A",
    certificate: "Abc Certificate Title",
    certificateImage: CertificateImg,
  },
  {
    id: 4,
    image: UserProfile,
    name: "Tom Albert",
    email: "tomalbert@gmail.com",
    number: "+19159969739",
    areaInterst: "Interest ABC, Interest ABC, Interest ABC",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.  tempor. Cum sociis natoque penatibus et magnis dis parturient.  Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar",
    institutename: "Institute ABC",
    degreeTitle: "Degree ABC",
    year: "2020 - 2023",
    OrganizationName: "Organization ABC",
    Designation: "Doctor A",
    certificate: "Abc Certificate Title",
    certificateImage: CertificateImg,
  },
];
export const Mentortable = [
  {
    id: 1,
    srNo: "01",
    UserImg: User,
    requeststatus: "Pending",
    requestid: "Abc-123",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "orem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
    mentorname: "Tom Albert",
    number: "+19159969739",
    areaInterst: "Interest ABC, Interest ABC, Interest ABC",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.  tempor. Cum sociis natoque penatibus et magnis dis parturient.  Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar",
    institutename: "Institute ABC",
    degreeTitle: "Degree ABC",
    year: "2020 - 2023",
    OrganizationName: "Organization ABC",
    Designation: "Doctor A",
    certificate: "Abc Certificate Title",
    certificateImage: CertificateImg,
  },
  {
    id: 2,
    srNo: "02",
    UserImg: User,
    requeststatus: "Rejected",
    requestid: "Abc-123",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "orem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
    mentorname: "Tom Albert",
    number: "+19159969739",
    areaInterst: "Interest ABC, Interest ABC, Interest ABC",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.  tempor. Cum sociis natoque penatibus et magnis dis parturient.  Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar",
    institutename: "Institute ABC",
    degreeTitle: "Degree ABC",
    year: "2020 - 2023",
    OrganizationName: "Organization ABC",
    Designation: "Doctor A",
    certificate: "Abc Certificate Title",
    certificateImage: CertificateImg,
  },
  {
    id: 3,
    srNo: "03",
    UserImg: User,
    requeststatus: "Requested",
    requestid: "Abc-123",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "orem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
    mentorname: "Tom Albert",
    number: "+19159969739",
    areaInterst: "Interest ABC, Interest ABC, Interest ABC",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.  tempor. Cum sociis natoque penatibus et magnis dis parturient.  Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar",
    institutename: "Institute ABC",
    degreeTitle: "Degree ABC",
    year: "2020 - 2023",
    OrganizationName: "Organization ABC",
    Designation: "Doctor A",
    certificate: "Abc Certificate Title",
    certificateImage: CertificateImg,
  },
  {
    id: 4,
    srNo: "04",
    UserImg: User,
    requeststatus: "Request - Accepted",
    requestid: "Abc-123",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "orem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
    mentorname: "Tom Albert",
    number: "+19159969739",
    areaInterst: "Interest ABC, Interest ABC, Interest ABC",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.  tempor. Cum sociis natoque penatibus et magnis dis parturient.  Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar",
    institutename: "Institute ABC",
    degreeTitle: "Degree ABC",
    year: "2020 - 2023",
    OrganizationName: "Organization ABC",
    Designation: "Doctor A",
    certificate: "Abc Certificate Title",
    certificateImage: CertificateImg,
  },
  {
    id: 5,
    srNo: "05",
    UserImg: User,
    requeststatus: "Request - Rejected",
    requestid: "Abc-123",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "orem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
    mentorname: "Tom Albert",
    number: "+19159969739",
    areaInterst: "Interest ABC, Interest ABC, Interest ABC",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.  tempor. Cum sociis natoque penatibus et magnis dis parturient.  Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar",
    institutename: "Institute ABC",
    degreeTitle: "Degree ABC",
    year: "2020 - 2023",
    OrganizationName: "Organization ABC",
    Designation: "Doctor A",
    certificate: "Abc Certificate Title",
    certificateImage: CertificateImg,
  },
  {
    id: 6,
    srNo: "06",
    UserImg: User,
    requeststatus: "Accepted",
    requestid: "Abc-123",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "orem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
    mentorname: "Tom Albert",
    number: "+19159969739",
    areaInterst: "Interest ABC, Interest ABC, Interest ABC",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.  tempor. Cum sociis natoque penatibus et magnis dis parturient.  Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar",
    institutename: "Institute ABC",
    degreeTitle: "Degree ABC",
    year: "2020 - 2023",
    OrganizationName: "Organization ABC",
    Designation: "Doctor A",
    certificate: "Abc Certificate Title",
    certificateImage: CertificateImg,
  },
  {
    id: 6,
    srNo: "06",
    UserImg: User,
    requeststatus: "Contacted",
    requestid: "Abc-123",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "orem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
    mentorname: "Tom Albert",
    number: "+19159969739",
    areaInterst: "Interest ABC, Interest ABC, Interest ABC",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.  tempor. Cum sociis natoque penatibus et magnis dis parturient.  Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar",
    institutename: "Institute ABC",
    degreeTitle: "Degree ABC",
    year: "2020 - 2023",
    OrganizationName: "Organization ABC",
    Designation: "Doctor A",
    certificate: "Abc Certificate Title",
    certificateImage: CertificateImg,
  },
];
export const accountTable = [
  {
    id: 1,
    srNo: "01",
    UserImg: User,
    requeststatus: "Pending",
    requestid: "Abc-123",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "orem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
    mentorname: "Tom Albert",
    number: "+19159969739",
    areaInterst: "Interest ABC, Interest ABC, Interest ABC",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.  tempor. Cum sociis natoque penatibus et magnis dis parturient.  Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar",
    institutename: "Institute ABC",
    degreeTitle: "Degree ABC",
    year: "2020 - 2023",
    OrganizationName: "Organization ABC",
    Designation: "Doctor A",
    certificate: "Abc Certificate Title",
    certificateImage: CertificateImg,
  },
  {
    id: 2,
    srNo: "02",
    UserImg: User,
    requeststatus: "Rejected",
    requestid: "Abc-123",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "orem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
    mentorname: "Tom Albert",
    number: "+19159969739",
    areaInterst: "Interest ABC, Interest ABC, Interest ABC",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.  tempor. Cum sociis natoque penatibus et magnis dis parturient.  Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar",
    institutename: "Institute ABC",
    degreeTitle: "Degree ABC",
    year: "2020 - 2023",
    OrganizationName: "Organization ABC",
    Designation: "Doctor A",
    certificate: "Abc Certificate Title",
    certificateImage: CertificateImg,
  },
  {
    id: 3,
    srNo: "03",
    UserImg: User,
    requeststatus: "Pending",
    requestid: "Abc-123",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "orem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
    mentorname: "Tom Albert",
    number: "+19159969739",
    areaInterst: "Interest ABC, Interest ABC, Interest ABC",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.  tempor. Cum sociis natoque penatibus et magnis dis parturient.  Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar",
    institutename: "Institute ABC",
    degreeTitle: "Degree ABC",
    year: "2020 - 2023",
    OrganizationName: "Organization ABC",
    Designation: "Doctor A",
    certificate: "Abc Certificate Title",
    certificateImage: CertificateImg,
  },
  {
    id: 4,
    srNo: "04",
    UserImg: User,
    requeststatus: "Rejected",
    requestid: "Abc-123",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "orem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
    mentorname: "Tom Albert",
    number: "+19159969739",
    areaInterst: "Interest ABC, Interest ABC, Interest ABC",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.  tempor. Cum sociis natoque penatibus et magnis dis parturient.  Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar",
    institutename: "Institute ABC",
    degreeTitle: "Degree ABC",
    year: "2020 - 2023",
    OrganizationName: "Organization ABC",
    Designation: "Doctor A",
    certificate: "Abc Certificate Title",
    certificateImage: CertificateImg,
  },
  {
    id: 5,
    srNo: "05",
    UserImg: User,
    requeststatus: "Pending",
    requestid: "Abc-123",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "orem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
    mentorname: "Tom Albert",
    number: "+19159969739",
    areaInterst: "Interest ABC, Interest ABC, Interest ABC",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.  tempor. Cum sociis natoque penatibus et magnis dis parturient.  Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar",
    institutename: "Institute ABC",
    degreeTitle: "Degree ABC",
    year: "2020 - 2023",
    OrganizationName: "Organization ABC",
    Designation: "Doctor A",
    certificate: "Abc Certificate Title",
    certificateImage: CertificateImg,
  },
  {
    id: 6,
    srNo: "06",
    UserImg: User,
    requeststatus: "Rejected",
    requestid: "Abc-123",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "orem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
    mentorname: "Tom Albert",
    number: "+19159969739",
    areaInterst: "Interest ABC, Interest ABC, Interest ABC",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.  tempor. Cum sociis natoque penatibus et magnis dis parturient.  Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar",
    institutename: "Institute ABC",
    degreeTitle: "Degree ABC",
    year: "2020 - 2023",
    OrganizationName: "Organization ABC",
    Designation: "Doctor A",
    certificate: "Abc Certificate Title",
    certificateImage: CertificateImg,
  },
  {
    id: 7,
    srNo: "07",
    UserImg: User,
    requeststatus: "Pending",
    requestid: "Abc-123",
    requestdate: "01/01/2022",
    goal: "abc Goal",
    expectation:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient.",
    email: "info@example.com",
    phone: "+40-123-456-789",
    areaofinterst: "Interest A, Interest B",
    aboutmantee:
      "orem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar        tempor. Cum sociis natoque penatibus et magnis dis parturient",
    mentorname: "Tom Albert",
    number: "+19159969739",
    areaInterst: "Interest ABC, Interest ABC, Interest ABC",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.  tempor. Cum sociis natoque penatibus et magnis dis parturient.  Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar",
    institutename: "Institute ABC",
    degreeTitle: "Degree ABC",
    year: "2020 - 2023",
    OrganizationName: "Organization ABC",
    Designation: "Doctor A",
    certificate: "Abc Certificate Title",
    certificateImage: CertificateImg,
  },
];
export const InterstManagementData = [
  {
    id: 1,
    srNo: "01",
    status: true,
    image: MenteeProfile,
    name: "Abc Ad Title",
    regDate: "01/01/2022",
  },
  {
    id: 2,
    srNo: "02",
    status: true,
    image: MenteeProfile,
    name: "Abc Ad Title",
    regDate: "01/01/2022",
  },
  {
    id: 3,
    srNo: "03",
    status: true,
    image: MenteeProfile,
    name: "Abv-123",
    regDate: "05/01/2021",
  },
  {
    id: 4,
    srNo: "04",
    image: MenteeProfile,
    phone: "+40-123-456-7890",
    status: false,
    name: "Abv-123",
    regDate: "01/01/2020",
  },
  {
    id: 5,
    srNo: "05",
    image: MenteeProfile,
    phone: "+40-123-456-7890",
    status: true,
    name: "Abv-123",
    regDate: "01/01/2022",
  },
  {
    id: 6,
    srNo: "06",
    image: MenteeProfile,
    phone: "+40-123-456-7890",
    status: false,
    name: "Abv-123",
    regDate: "01/01/2022",
  },
];
export const AdsSubscriptiionData = [
  {
    id: 1,
    srNo: "01",
    status: true,
    PackageTitle: "Abc Package",
    regDate: "01/01/2022",
    noofReq: "20",
    about:
      " Lorem ipsum dolor sit amet consectetur, adipisicing elit. Pariatur adipisci reiciendis reprehenderit saepe? Et atque laborum optio nihil quasi! Deleniti.",
    Amount: "$123",
  },
  {
    id: 2,
    srNo: "02",
    status: true,
    PackageTitle: "Abc Ad Title",
    regDate: "01/01/2022",
    noofReq: "20",
    about:
      " Lorem ipsum dolor sit amet consectetur, adipisicing elit. Pariatur adipisci reiciendis reprehenderit saepe? Et atque laborum optio nihil quasi! Deleniti.",
    Amount: "$123",
  },
  {
    id: 3,
    srNo: "03",
    status: true,
    PackageTitle: "Abv-123",
    noofReq: "20",
    about:
      " Lorem ipsum dolor sit amet consectetur, adipisicing elit. Pariatur adipisci reiciendis reprehenderit saepe? Et atque laborum optio nihil quasi! Deleniti.",
    regDate: "05/01/2021",
    Amount: "$123",
  },
  {
    id: 4,
    srNo: "04",
    status: false,
    PackageTitle: "Abv-123",
    noofReq: "20",
    about:
      " Lorem ipsum dolor sit amet consectetur, adipisicing elit. Pariatur adipisci reiciendis reprehenderit saepe? Et atque laborum optio nihil quasi! Deleniti.",
    regDate: "01/01/2020",
    Amount: "$123",
  },
  {
    id: 5,
    srNo: "05",
    status: true,
    PackageTitle: "Abv-123",
    regDate: "01/01/2022",
    noofReq: "20",
    about:
      " Lorem ipsum dolor sit amet consectetur, adipisicing elit. Pariatur adipisci reiciendis reprehenderit saepe? Et atque laborum optio nihil quasi! Deleniti.",
    Amount: "$123",
  },
  {
    id: 6,
    srNo: "06",
    status: false,
    PackageTitle: "Abv-123",
    regDate: "01/01/2022",
    noofReq: "20",
    about:
      " Lorem ipsum dolor sit amet consectetur, adipisicing elit. Pariatur adipisci reiciendis reprehenderit saepe? Et atque laborum optio nihil quasi! Deleniti.",
    Amount: "$123",
  },
];
export const FeeData = [
  {
    id: 1,
    srNo: "01",
    fees: "$20",
    updateon: "01-01-2023",
  },
  {
    id: 2,
    srNo: "02",
    fees: "$20",
    updateon: "01-01-2023",
  },
  {
    id: 3,
    srNo: "03",
    fees: "$20",
    updateon: "01-01-2023",
  },
  {
    id: 4,
    srNo: "04",
    fees: "$20",
    updateon: "01-01-2023",
  },
];
export const QueriesData = [
  {
    id: 1,
    srNo: "01",
    UserImg: User,
    name: "Mark Jeson",
    email: "info@example.com",
    userType: "Guest",
    date: "01/01/2022",
    subject: "Abc Subject",
    message:
      "Lorem Ipsum Dolor Sit Amet, Consectetur Adipiscing Elit. Aenean Euismod Bibendum Laoreet. Proin Gravida Dolor Sit Amet Lacus Accumsan Et Viverra Justo Commodo. Proin Sodales Pulvinar Tempor. Cum Sociis Natoque Penatibus Et Magnis Dis Parturient.",
  },
  {
    id: 2,
    srNo: "02",
    UserImg: User,
    name: "Mark Jeson",
    email: "info@example.com",
    userType: "Home",
    date: "01/01/2022",
    subject: "Abc Subject",
    message:
      "Lorem Ipsum Dolor Sit Amet, Consectetur Adipiscing Elit. Aenean Euismod Bibendum Laoreet. Proin Gravida Dolor Sit Amet Lacus Accumsan Et Viverra Justo Commodo. Proin Sodales Pulvinar Tempor. Cum Sociis Natoque Penatibus Et Magnis Dis Parturient.",
  },
  {
    id: 3,
    srNo: "03",
    UserImg: User,
    name: "Mark Jeson",
    email: "info@example.com",
    userType: "Mentor",
    date: "01/01/2022",
    subject: "Abc Subject",
    message:
      "Lorem Ipsum Dolor Sit Amet, Consectetur Adipiscing Elit. Aenean Euismod Bibendum Laoreet. Proin Gravida Dolor Sit Amet Lacus Accumsan Et Viverra Justo Commodo. Proin Sodales Pulvinar Tempor. Cum Sociis Natoque Penatibus Et Magnis Dis Parturient.",
  },
  {
    id: 4,
    srNo: "04",
    UserImg: User,
    name: "jason roy",
    email: "info@example.com",
    userType: "Mentee",
    date: "01/01/2022",
    subject: "Abc Subject",
    message:
      "Lorem Ipsum Dolor Sit Amet, Consectetur Adipiscing Elit. Aenean Euismod Bibendum Laoreet. Proin Gravida Dolor Sit Amet Lacus Accumsan Et Viverra Justo Commodo. Proin Sodales Pulvinar Tempor. Cum Sociis Natoque Penatibus Et Magnis Dis Parturient.",
  },
  {
    id: 5,
    srNo: "05",
    UserImg: User,
    name: "Mark hood",
    email: "info@example.com",
    userType: "Mentor",
    date: "01/01/2022",
    subject: "Abc Subject",
    message:
      "Lorem Ipsum Dolor Sit Amet, Consectetur Adipiscing Elit. Aenean Euismod Bibendum Laoreet. Proin Gravida Dolor Sit Amet Lacus Accumsan Et Viverra Justo Commodo. Proin Sodales Pulvinar Tempor. Cum Sociis Natoque Penatibus Et Magnis Dis Parturient.",
  },
];
export const PaymentLogsData = [
  {
    addsubs: [
      {
        id: 1,
        srNo: "01",
        status: true,
        name: "Mark Jeson",
        image: UserProfile,
        AdTitle: "Abv-123",
        subsdate: "01-01-20203",
        ReqRicived: "20",
        RemainingRequests: "20",
      },
      {
        id: 2,
        srNo: "02",
        status: false,
        name: "Mark Jeson",
        image: UserProfile,
        AdTitle: "Abv-123",
        subsdate: "01-01-20203",
        ReqRicived: "20",
        RemainingRequests: "20",
      },
      {
        id: 3,
        srNo: "03",
        status: false,
        name: "Mark Jeson",
        image: UserProfile,
        AdTitle: "Abv-123",
        subsdate: "01-01-20203",
        ReqRicived: "20",
        RemainingRequests: "20",
      },
      {
        id: 4,
        srNo: "04",
        status: false,
        name: "Mark Jeson",
        image: UserProfile,
        AdTitle: "Abv-123",
        subsdate: "01-01-20203",
        ReqRicived: "20",
        RemainingRequests: "20",
      },
      {
        id: 5,
        srNo: "05",
        status: false,
        name: "Mark Jeson",
        image: UserProfile,
        AdTitle: "Abv-123",
        subsdate: "01-01-20203",
        ReqRicived: "20",
        RemainingRequests: "20",
      },
    ],
    FeaturingSubscription: [
      {
        id: 1,
        srNo: "01",
        status: true,
        name: "Mark Jeson",
        image: UserProfile,
        AdTitle: "Abv-123",
        subsdate: "01-01-20203",
        ReqRicived: "20",
        RemainingRequests: "20",
      },
      {
        id: 2,
        srNo: "02",
        status: false,
        name: "Mark Jeson",
        image: UserProfile,
        AdTitle: "Abv-123",
        subsdate: "01-01-20203",
        ReqRicived: "20",
        RemainingRequests: "20",
      },
      {
        id: 3,
        srNo: "03",
        status: true,
        name: "Mark Jeson",
        image: UserProfile,
        AdTitle: "Abv-123",
        subsdate: "01-01-20203",
        ReqRicived: "20",
        RemainingRequests: "20",
      },
      {
        id: 4,
        srNo: "04",
        status: false,
        name: "Mark Jeson",
        image: UserProfile,
        AdTitle: "Abv-123",
        subsdate: "01-01-20203",
        ReqRicived: "20",
        RemainingRequests: "20",
      },
      {
        id: 5,
        srNo: "05",
        status: true,
        name: "Mark Jeson",
        image: UserProfile,
        AdTitle: "Abv-123",
        subsdate: "01-01-20203",
        ReqRicived: "20",
        RemainingRequests: "20",
      },
    ],
    Mentorshiprequests: [
      {
        id: 1,
        srNo: "01",
        status: true,
        mentorname: "Mark Jeson",
        menteename: "jason roy",
        image: UserProfile,
        reqId: "#20123",
        subsdate: "01-01-20203",
        amount: "$20",
      },
      {
        id: 2,
        srNo: "02",
        status: false,
        mentorname: "Mark Jeson",
        menteename: "jason roy",
        image: UserProfile,
        reqId: "#26123",
        subsdate: "01-01-20203",
        amount: "$25",
      },
      {
        id: 3,
        srNo: "03",
        status: false,
        mentorname: "Mark Jeson",
        menteename: "jason roy",
        image: UserProfile,
        reqId: "#26123",
        subsdate: "01-01-20203",
        amount: "$25",
      },
      {
        id: 4,
        srNo: "04",
        status: true,
        mentorname: "Mark Jeson",
        menteename: "jason roy",
        image: UserProfile,
        reqId: "#86123",
        subsdate: "01-01-20203",
        amount: "$55",
      },
      {
        id: 5,
        srNo: "05",
        status: false,
        mentorname: "Mark Jeson",
        menteename: "jason roy",
        image: UserProfile,
        reqId: "#26123",
        subsdate: "01-01-20203",
        amount: "$25",
      },
    ],
  },
];
export const adminProfileData = {
  image: UserProfile,
  firstname: "Mark",
  lastname: "jeson",
  email: "tomalbert@gmail.com",
  number: "+19159969739",
};
export const menteeProfileDataa = {
  image: UserProfile,
  name: "Mark Jeson",
  email: "Tomalbert@Gmail.Com",
  number: "+19159969739",
  areaInterst: "Interest ABC, Interest ABC, Interest ABC",
  about:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.  tempor. Cum sociis natoque penatibus et magnis dis parturient.  Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar",
  institutename: "Institute ABC",
  degreeTitle: "Degree ABC",
  year: "2020 - 2023",
  OrganizationName: "Organization ABC",
  Designation: "Doctor A",
  certificate: "Abc Certificate Title",
  certificateImage: CertificateImg,
};
// Admin data End here
